# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import microservices_Auth_pb2 as microservices__Auth__pb2


class AccessControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_stream(
                '/AuthCore.AccessControl/List',
                request_serializer=microservices__Auth__pb2.UserListRequest.SerializeToString,
                response_deserializer=microservices__Auth__pb2.Access.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/AuthCore.AccessControl/Retrieve',
                request_serializer=microservices__Auth__pb2.UserRetrieveRequest.SerializeToString,
                response_deserializer=microservices__Auth__pb2.Access.FromString,
                )


class AccessControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_stream_rpc_method_handler(
                    servicer.List,
                    request_deserializer=microservices__Auth__pb2.UserListRequest.FromString,
                    response_serializer=microservices__Auth__pb2.Access.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=microservices__Auth__pb2.UserRetrieveRequest.FromString,
                    response_serializer=microservices__Auth__pb2.Access.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthCore.AccessControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AuthCore.AccessControl/List',
            microservices__Auth__pb2.UserListRequest.SerializeToString,
            microservices__Auth__pb2.Access.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AuthCore.AccessControl/Retrieve',
            microservices__Auth__pb2.UserRetrieveRequest.SerializeToString,
            microservices__Auth__pb2.Access.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
